name: Generate and Test gRPC Stubs

on:
  push:
    paths:
      - 'proto/**'
      - '.github/workflows/**'
      - 'version.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      ##################################################
      # 1) CHECK OUT REPO AND SET VERSION
      ##################################################
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set common version
        id: version
        run: |
          # Read version from version.txt file
          VERSION=$(cat version.txt | tr -d '\n\r\t ')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Common version set to: $VERSION"
          
          # For auto-versioning based on commits, uncomment these lines
          # COMMIT_COUNT=$(git rev-list --count HEAD)
          # VERSION="1.0.$COMMIT_COUNT"
          # echo "VERSION=$VERSION" >> $GITHUB_ENV
          # echo "Auto-generated version: $VERSION"
          # echo "$VERSION" > version.txt

      ##################################################
      # 2) GENERATE PYTHON STUBS
      ##################################################
      # Note: We generate a simple __init__.py with explicit imports
      # instead of using dynamic imports to avoid issues with relative imports
      # when the package is installed as a dependency
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Python gRPC tools
        run: |
          pip install --upgrade pip
          pip install grpcio-tools

      - name: Create Python output directory
        run: mkdir -p ./generated/compsci399_grpc

      - name: Generate Python code
        run: |
          python -m grpc_tools.protoc \
            -I=./proto \
            --python_out=./generated/compsci399_grpc \
            --grpc_python_out=./generated/compsci399_grpc \
            ./proto/*.proto

      - name: Create simplified __init__.py
        run: |
          # Remove existing __init__.py if it exists
          rm -f ./generated/compsci399_grpc/__init__.py
          
          # Create a new __init__.py with explicit imports
          python -c '
          import os
          import glob

          init_content = "# Auto-generated explicit imports\n"
          init_content += f"__version__ = \"${{ env.VERSION }}\"\n\n"
          
          # Get all proto files
          proto_files = glob.glob("./proto/*.proto")
          proto_base_names = [os.path.splitext(os.path.basename(f))[0] for f in proto_files]
          
          # Add explicit imports for each proto module
          for name in sorted(proto_base_names):
              init_content += f"from .{name}_pb2 import *\n"
              init_content += f"from .{name}_pb2_grpc import *\n"
          
          # Write the file
          with open("./generated/compsci399_grpc/__init__.py", "w") as f:
              f.write(init_content)
          
          print(f"Created __init__.py with imports for: {", ".join(proto_base_names)})")
          '

      - name: Fix Python gRPC imports
        run: |
          # Find and fix all *_pb2_grpc.py files to use relative imports
          python -c '
          import os
          import glob
          import re
          
          # Find all *_pb2_grpc.py files
          grpc_files = glob.glob("./generated/compsci399_grpc/*_pb2_grpc.py")
          
          for file_path in grpc_files:
              with open(file_path, "r") as f:
                  content = f.read()
              
              # Replace imports like "import X_pb2 as X__pb2" with "from . import X_pb2 as X__pb2"
              fixed_content = re.sub(
                  r"import (\w+_pb2) as (\w+__pb2)",
                  r"from . import \1 as \2",
                  content
              )
              
              # Write the file back
              with open(file_path, "w") as f:
                  f.write(fixed_content)
              
              print(f"Fixed imports in {os.path.basename(file_path)}")
          '

      - name: Update Python setup.py with version
        run: |
          # Update setup.py with the common version
          cat > setup.py << EOF
          from setuptools import setup
          import os
          import shutil

          # Define source and target directories
          source_dir = 'generated/compsci399_grpc'
          target_dir = 'compsci399_grpc'

          # Copy the files if source directory exists and target doesn't
          if os.path.exists(source_dir) and not os.path.exists(target_dir):
              # Create the directory and copy files
              shutil.copytree(source_dir, target_dir)
              print(f"Successfully copied {source_dir} to {target_dir}")
          elif os.path.exists(target_dir):
              # Target directory already exists, no need to copy
              print(f"Using existing {target_dir} directory")
          elif not os.path.exists(source_dir) and not os.path.exists(target_dir):
              # This is likely in the build environment of CI/CD
              # The source directory doesn't exist, and the package files weren't copied yet
              # Create an empty package directory to avoid build errors
              # This will be replaced by the actual files during installation
              os.makedirs(target_dir, exist_ok=True)
              # Create an __init__.py file to make it a valid package
              with open(os.path.join(target_dir, '__init__.py'), 'w') as f:
                  f.write('# Placeholder file for build process\\n')
              print(f"Created placeholder package in {target_dir}")

          setup(
              name="compsci399-grpc",
              version="${{ env.VERSION }}",
              packages=["compsci399_grpc"],
              install_requires=[
                  "grpcio>=1.44.0",
                  "protobuf>=3.19.0"
              ],
              package_data={"compsci399_grpc": ["*.py"]},
              description='Generated gRPC Python stubs for my service',
          )
          EOF
          
          # Create MANIFEST.in to include version.txt
          cat > MANIFEST.in << EOF
          include version.txt
          include README.md
          EOF

      - name: Copy generated Python files to root level package
        run: |
          # Ensure we have the compsci399_grpc directory at root level
          mkdir -p compsci399_grpc
          
          # Copy all Python files from generated/compsci399_grpc to compsci399_grpc
          cp -R generated/compsci399_grpc/* compsci399_grpc/
          
          echo "Copied generated files to root-level package directory"
          ls -la compsci399_grpc/

      - name: Install Python build tools
        run: |
          pip install build twine

      ##################################################
      # 2.1) BUILD AND PUBLISH PYTHON PACKAGE TO PYPI
      ##################################################
      - name: Build Python package
        run: |
          python -m build

      - name: Publish Python package to PyPI
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*

      ##################################################
      # 3) GENERATE NODE.JS / TYPESCRIPT STUBS
      ##################################################
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Node dev dependencies
        run: |
          npm install --global grpc-tools @grpc/proto-loader ts-protoc-gen

      - name: Create Node output directory
        run: mkdir -p ./generated/node

      - name: Generate Node stubs
        run: |
          grpc_tools_node_protoc \
            --plugin=protoc-gen-ts=$(which protoc-gen-ts) \
            --js_out=import_style=commonjs,binary:./generated/node \
            --ts_out=service=grpc-node:./generated/node \
            --grpc_out=grpc_js:./generated/node \
            --plugin=protoc-gen-grpc=$(which grpc_tools_node_protoc_plugin) \
            -I=./proto \
            ./proto/*.proto

      ##################################################
      # 4) GENERATE C# STUBS
      ##################################################
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install Protobuf compiler and C# gRPC tools
        id: install-tools
        run: |
          # Install protobuf compiler
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

          # Create a temporary project to install gRPC tools packages
          mkdir -p ./temp-project
          cd ./temp-project
          dotnet new console
          dotnet add package Grpc.Tools
          dotnet add package Google.Protobuf
          
          # Find the path to grpc_csharp_plugin in NuGet packages
          NUGET_DIR=~/.nuget/packages
          GRPC_TOOLS_VERSION=$(dotnet list package | grep Grpc.Tools | awk '{print $4}')
          TOOL_PATH="${NUGET_DIR}/grpc.tools/${GRPC_TOOLS_VERSION}/tools/linux_x64/grpc_csharp_plugin"
          
          if [ -f "$TOOL_PATH" ]; then
            echo "Found gRPC C# plugin at: $TOOL_PATH"
            chmod +x "$TOOL_PATH"
            # Set the output for other steps to use
            echo "plugin_path=$TOOL_PATH" >> "$GITHUB_OUTPUT"
          else
            echo "ERROR: Could not find grpc_csharp_plugin at expected path: $TOOL_PATH"
            echo "Searching for it in the NuGet packages directory..."
            find $NUGET_DIR -name "grpc_csharp_plugin" -type f
            exit 1
          fi
          
          cd ..

      - name: Create C# output directory
        run: mkdir -p ./generated/csharp

      - name: Generate C# code
        run: |
          protoc \
            --csharp_out=./generated/csharp \
            --grpc_out=./generated/csharp \
            --plugin=protoc-gen-grpc=${{ steps.install-tools.outputs.plugin_path }} \
            -I=./proto \
            ./proto/*.proto
          
          # Clean up temporary project
          rm -rf ./temp-project

      ##################################################
      # 5) PACKAGE AND PUBLISH C# CODE TO NUGET
      ##################################################
      - name: Create C# NuGet package project
        run: |
          # Create a class library project for the NuGet package
          dotnet new classlib -n Compsci399Grpc -o ./generated/csharp-package --force
          cd ./generated/csharp-package
          
          # Edit the project file to include necessary properties
          cat > Compsci399Grpc.csproj << EOF
          <Project Sdk="Microsoft.NET.Sdk">
            <PropertyGroup>
              <TargetFramework>net8.0</TargetFramework>
              <ImplicitUsings>enable</ImplicitUsings>
              <Nullable>enable</Nullable>
              <PackageId>Compsci399Grpc</PackageId>
              <Version>${{ env.VERSION }}</Version>
              <Authors>gRPC Generator</Authors>
              <Company>COMPSCI399</Company>
              <Description>Auto-generated gRPC client stubs</Description>
              <PackageLicenseExpression>MIT</PackageLicenseExpression>
              <RepositoryUrl>https://github.com/capstone2025uoa/grpc</RepositoryUrl>
              <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
              <PackageListedStatus>Hidden</PackageListedStatus>
              <PackageReadmeFile>README.md</PackageReadmeFile>
            </PropertyGroup>
            <ItemGroup>
              <PackageReference Include="Google.Protobuf" Version="3.29.3" />
              <PackageReference Include="Grpc.Net.Client" Version="2.67.0" />
              <PackageReference Include="Grpc.Tools" Version="2.70.0" PrivateAssets="All" />
            </ItemGroup>
            <ItemGroup>
              <None Include="README.md" Pack="true" PackagePath="\" />
            </ItemGroup>
          </Project>
          EOF
          
          # Create README.md with the main content
          echo "# Compsci399Grpc" > README.md
          echo "" >> README.md
          echo "This package contains auto-generated gRPC client stubs for use with the COMPSCI399 services." >> README.md
          echo "" >> README.md
          echo "## Installation" >> README.md
          echo "" >> README.md
          echo "\`\`\`bash" >> README.md
          echo "dotnet add package Compsci399Grpc" >> README.md
          echo "\`\`\`" >> README.md
          echo "" >> README.md
          echo "## Usage" >> README.md
          echo "" >> README.md
          echo "\`\`\`csharp" >> README.md
          echo "using Compsci399Grpc;" >> README.md
          echo "using Grpc.Net.Client;" >> README.md
          echo "" >> README.md
          echo "// Create a gRPC channel" >> README.md
          echo "using var channel = GrpcChannel.ForAddress(\"https://your-grpc-service-url\");" >> README.md
          echo "" >> README.md
          echo "// Create a client for the specific service you want to use" >> README.md
          echo "// Example for a Greeter service:" >> README.md
          echo "var client = new Greeter.GreeterClient(channel);" >> README.md
          echo "" >> README.md
          echo "## Available Services" >> README.md
          echo "" >> README.md
          
          # Find services and append to README
          find ../csharp -name "*Grpc.cs" | xargs grep "public class" | sed 's/.*public class //g' | sed 's/ :.*//g' | sort | uniq | sed 's/^/- /g' >> README.md
          
          # Add version history and license
          echo "" >> README.md
          echo "## Version History" >> README.md
          echo "" >> README.md
          echo "- ${{ env.VERSION }}: Current release" >> README.md
          echo "" >> README.md
          echo "## License" >> README.md
          echo "" >> README.md
          echo "MIT" >> README.md

      - name: Copy generated C# files to package project
        run: |
          # Copy all the generated .cs files to the package project
          cp ./generated/csharp/*.cs ./generated/csharp-package/
          
          # Remove Class1.cs that comes with the template
          rm -f ./generated/csharp-package/Class1.cs

      - name: Build and pack NuGet package
        run: |
          cd ./generated/csharp-package
          dotnet build -c Release
          dotnet pack -c Release -o ./nupkg

      - name: Publish NuGet package
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          cd ./generated/csharp-package/nupkg
          # Replace API_KEY with your actual NuGet API key stored in GitHub secrets
          dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate

      ##################################################
      # 6) PACKAGE AND PUBLISH NODE.JS / TYPESCRIPT TO NPM
      ##################################################
      - name: Generate dynamic index files for Node package
        run: |
          # Make the script executable if not already
          chmod +x ./scripts/generate-index.js
          
          # Run the script to generate index.js and index.d.ts
          node ./scripts/generate-index.js

      - name: Update Node package version
        run: |
          # Get current version from package.json
          CURRENT_VERSION=$(node -e "console.log(require('./package.json').version)")
          
          # Only update version if different
          if [ "$CURRENT_VERSION" != "${{ env.VERSION }}" ]; then
            echo "Updating npm package version from $CURRENT_VERSION to ${{ env.VERSION }}"
            npm version ${{ env.VERSION }} --no-git-tag-version --allow-same-version
          else
            echo "Package.json version already at ${{ env.VERSION }}, no update needed"
          fi

      - name: Publish to npm
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      ##################################################
      # 7) COMMIT GENERATED FILES BACK TO REPO
      ##################################################
      - name: Commit generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update generated gRPC stubs [skip ci]"
          file_pattern: "generated/** compsci399_grpc/** index.js index.d.ts package.json setup.py MANIFEST.in"
